# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BonSci
email: voteclustering@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  BonSci is a set of frameworks for gathering and summarizing human intuitions and opinions.
  
  
  
baseurl: "" #"/bonsci.jp.github.io" #"/bonsci.jp.github.io" # the subpath of your site, e.g. /blog
url: "https://bonsci.github.io" # the base hostname & protocol for your site

#sidebar
default-image: bonsci-logo-big.png # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: Tatsuro Kawamoto
copyright:
   name: Tatsuro Kawamoto
   link: 'http://tatsuro-kawamoto.github.io'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: UA-83979019-1

# Comments
#disqus-shortname: webjeda-demo

#social
facebook: https://www.facebook.com/tatsuro.kawamoto
#quora: http://quora.com/sharathdt
twitter: http://twitter.com/@tatmann9
github: http://github.com/tatsuro-kawamoto

#facebook like box
fb-app-id: 179887139237036 # 549480635219583
fb-page-url: https://www.facebook.com/BonSciJapan/
fb-page-title: BonSci

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]

